### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by KevM92** [gabrielweyer/azure-vm-pricing#280]
Hey @gabrielweyer 
I tried grabbing a few configs, but just with this config, I got a Timeout:
`yarn crawl --culture de-de --currency eur --operating-system windows --region europe-west --output-path .\out\`

I get this kind of timeout: 
```
C:\_GitHub\azure-vm-pricing\parser\node_modules\puppeteer-core\src\common\WaitTask.ts:82
      this.#timeoutError = new TimeoutError(
                           ^
TimeoutError: Waiting failed: 3000ms exceeded
    at new WaitTask (C:\_GitHub\azure-vm-pricing\parser\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\_GitHub\azure-vm-pricing\parser\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\_GitHub\azure-vm-pricing\parser\node_modules\puppeteer-core\src\api\Frame.ts:777:36)
    at CdpFrame.<anonymous> (C:\_GitHub\azure-vm-pricing\parser\node_modules\puppeteer-core\src\util\decorators.ts:63:21)
    at CdpPage.waitForFunction (C:\_GitHub\azure-vm-pricing\parser\node_modules\puppeteer-core\src\api\Page.ts:3011:29)
    at AzurePortal.waitForPriceWithoutHybridBenefits (C:\_GitHub\azure-vm-pricing\parser\src\azurePortalExtensions.ts:207:18)
    at AzurePortal.hideAzureHybridBenefit (C:\_GitHub\azure-vm-pricing\parser\src\azurePortalExtensions.ts:194:16)
    at async AzurePortal.parsePricing (C:\_GitHub\azure-vm-pricing\parser\src\azurePortalExtensions.ts:76:7)
    at async C:\_GitHub\azure-vm-pricing\parser\src\app.ts:242:23 
```

Do you have an idea how I could solve this? 

I downloaded the following without any issue.
```
yarn crawl --culture de-de --currency eur --operating-system windows --region germany-west-central --output-path .\out\
yarn crawl --culture de-de --currency eur --operating-system linux --region germany-west-central --output-path .\out\
yarn crawl --culture de-de --currency eur --operating-system linux --region europe-west --output-path .\out\
```

**Comment by gabrielweyer** [comment]
This is because the portal is "helpfully" displaying a popup advising to select a cheaper region when picking this combination of parameters and the popup hides the hybrid benefits control:

![image](https://github.com/user-attachments/assets/6f6861f3-7679-472a-ae97-273b30c50e96)

This should have been fixed now.

**Comment by KevM92** [comment]
Can confirm this is fixed. Thank you!
